import { Category, Product } from './types';

export const categories: Category[] = [
  {
    id: '1',
    name: 'Mobile Accessories',
    slug: 'mobile-accessories',
    icon: 'Smartphone',
    subCategories: [
      { id: '1-1', name: 'Phone Cases', slug: 'phone-cases' },
      { id: '1-2', name: 'Screen Protectors', slug: 'screen-protectors' },
      { id: '1-3', name: 'Power Banks', slug: 'power-banks' },
      { id: '1-4', name: 'Chargers & Cables', slug: 'chargers-cables' },
      { id: '1-5', name: 'Car Mounts', slug: 'car-mounts' },
    ],
  },
  {
    id: '2',
    name: 'Audio Devices',
    slug: 'audio-devices',
    icon: 'Headphones',
    subCategories: [
      { id: '2-1', name: 'Wireless Earbuds', slug: 'wireless-earbuds' },
      { id: '2-2', name: 'Headphones', slug: 'headphones' },
      { id: '2-3', name: 'Bluetooth Speakers', slug: 'bluetooth-speakers' },
      { id: '2-4', name: 'Gaming Headsets', slug: 'gaming-headsets' },
    ],
  },
  {
    id: '3',
    name: 'Computer Accessories',
    slug: 'computer-accessories',
    icon: 'Monitor',
    subCategories: [
      { id: '3-1', name: 'Keyboards', slug: 'keyboards' },
      { id: '3-2', name: 'Mice', slug: 'mice' },
      { id: '3-3', name: 'Webcams', slug: 'webcams' },
      { id: '3-4', name: 'USB Hubs', slug: 'usb-hubs' },
      { id: '3-5', name: 'Laptop Stands', slug: 'laptop-stands' },
    ],
  },
  {
    id: '4',
    name: 'Gaming Gear',
    slug: 'gaming-gear',
    icon: 'Gamepad2',
    subCategories: [
      { id: '4-1', name: 'Gaming Keyboards', slug: 'gaming-keyboards' },
      { id: '4-2', name: 'Gaming Mice', slug: 'gaming-mice' },
      { id: '4-3', name: 'Mouse Pads', slug: 'mouse-pads' },
      { id: '4-4', name: 'Controllers', slug: 'controllers' },
    ],
  },
  {
    id: '5',
    name: 'Storage & Memory',
    slug: 'storage-memory',
    icon: 'HardDrive',
    subCategories: [
      { id: '5-1', name: 'External SSDs', slug: 'external-ssds' },
      { id: '5-2', name: 'Flash Drives', slug: 'flash-drives' },
      { id: '5-3', name: 'Memory Cards', slug: 'memory-cards' },
      { id: '5-4', name: 'External HDDs', slug: 'external-hdds' },
    ],
  },
  {
    id: '6',
    name: 'Wearables',
    slug: 'wearables',
    icon: 'Watch',
    subCategories: [
      { id: '6-1', name: 'Smart Watches', slug: 'smart-watches' },
      { id: '6-2', name: 'Fitness Trackers', slug: 'fitness-trackers' },
      { id: '6-3', name: 'Watch Bands', slug: 'watch-bands' },
    ],
  },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Premium Silicone Phone Case',
    slug: 'premium-silicone-phone-case',
    description: 'Protect your phone with our premium silicone case. Features shock-absorption technology and a slim design that fits perfectly in your hand.',
    shortDescription: 'Slim, protective silicone case with shock absorption',
    categoryId: '1',
    subCategoryId: '1-1',
    price: 1299,
    discountPrice: 999,
    discountPercentage: 23,
    images: ['phone-case', 'phone-accessories', 'mobile-protection'],
    inStock: true,
    stockQuantity: 150,
    isOnSale: true,
    isFeatured: true,
    isNew: false,
    variants: [
      {
        type: 'Color',
        options: [
          { name: 'Black', inStock: true },
          { name: 'Blue', inStock: true },
          { name: 'Red', inStock: true },
          { name: 'Clear', inStock: false },
        ],
      },
      {
        type: 'Model',
        options: [
          { name: 'iPhone 15 Pro', inStock: true },
          { name: 'iPhone 15', inStock: true },
          { name: 'Samsung S24', inStock: true },
          { name: 'Pixel 8', inStock: true },
        ],
      },
    ],
    specifications: {
      'Material': 'Premium Silicone',
      'Drop Protection': 'Up to 6 feet',
      'Weight': '28g',
      'Wireless Charging': 'Compatible',
    },
    rating: 4.5,
    reviewCount: 234,
    sku: 'PSC-001',
  },
  {
    id: '2',
    name: 'Wireless Earbuds Pro',
    slug: 'wireless-earbuds-pro',
    description: 'Experience premium sound quality with active noise cancellation. 30-hour battery life with charging case. IPX5 water resistance for workouts.',
    shortDescription: 'ANC wireless earbuds with 30hr battery',
    categoryId: '2',
    subCategoryId: '2-1',
    price: 8999,
    discountPrice: 6999,
    discountPercentage: 22,
    images: ['wireless-earbuds', 'audio-headphones', 'earphones-black'],
    inStock: true,
    stockQuantity: 87,
    isOnSale: true,
    isFeatured: true,
    isNew: true,
    variants: [
      {
        type: 'Color',
        options: [
          { name: 'Black', inStock: true },
          { name: 'White', inStock: true },
          { name: 'Blue', inStock: false },
        ],
      },
    ],
    specifications: {
      'Driver Size': '10mm',
      'Bluetooth': '5.3',
      'Battery Life': '30 hours (with case)',
      'Water Resistance': 'IPX5',
      'ANC': 'Yes',
    },
    rating: 4.7,
    reviewCount: 567,
    sku: 'WEP-002',
  },
  {
    id: '3',
    name: '20000mAh Fast Charging Power Bank',
    slug: 'fast-charging-power-bank-20000mah',
    description: 'Keep your devices charged on the go with this high-capacity power bank. Features 30W fast charging and can charge up to 3 devices simultaneously.',
    shortDescription: 'High-capacity 20000mAh power bank with fast charging',
    categoryId: '1',
    subCategoryId: '1-3',
    price: 3499,
    images: ['power-bank', 'portable-charger', 'battery-pack'],
    inStock: true,
    stockQuantity: 45,
    isOnSale: false,
    isFeatured: true,
    isNew: false,
    specifications: {
      'Capacity': '20000mAh',
      'Input': 'USB-C 30W',
      'Output': '2x USB-A, 1x USB-C',
      'Fast Charging': 'PD 3.0, QC 3.0',
      'Weight': '420g',
    },
    rating: 4.6,
    reviewCount: 892,
    sku: 'PB-003',
  },
  {
    id: '4',
    name: 'Mechanical Gaming Keyboard RGB',
    slug: 'mechanical-gaming-keyboard-rgb',
    description: 'Professional gaming keyboard with Cherry MX Blue switches. Full RGB backlight with multiple effects. Anti-ghosting and N-key rollover for competitive gaming.',
    shortDescription: 'RGB mechanical keyboard for gaming',
    categoryId: '4',
    subCategoryId: '4-1',
    price: 7999,
    discountPrice: 5999,
    discountPercentage: 25,
    images: ['gaming-keyboard', 'mechanical-keyboard', 'rgb-keyboard'],
    inStock: true,
    stockQuantity: 34,
    isOnSale: true,
    isFeatured: true,
    isNew: false,
    variants: [
      {
        type: 'Switch Type',
        options: [
          { name: 'Blue (Clicky)', inStock: true },
          { name: 'Red (Linear)', inStock: true },
          { name: 'Brown (Tactile)', inStock: false },
        ],
      },
    ],
    specifications: {
      'Switch Type': 'Cherry MX',
      'Backlight': 'RGB',
      'Connection': 'Wired USB-C',
      'Anti-ghosting': 'Yes',
      'Key Rollover': 'N-key',
    },
    rating: 4.8,
    reviewCount: 423,
    sku: 'GKB-004',
  },
  {
    id: '5',
    name: 'Wireless Gaming Mouse 16000 DPI',
    slug: 'wireless-gaming-mouse-16000-dpi',
    description: 'Ultra-precise gaming mouse with customizable DPI up to 16000. Ergonomic design with 8 programmable buttons. 70-hour battery life.',
    shortDescription: 'High-precision wireless gaming mouse',
    categoryId: '4',
    subCategoryId: '4-2',
    price: 4999,
    discountPrice: 3999,
    discountPercentage: 20,
    images: ['gaming-mouse', 'wireless-mouse', 'computer-mouse'],
    inStock: true,
    stockQuantity: 67,
    isOnSale: true,
    isFeatured: false,
    isNew: true,
    specifications: {
      'DPI': 'Up to 16000',
      'Buttons': '8 programmable',
      'Battery': '70 hours',
      'Connectivity': 'Wireless 2.4GHz + Bluetooth',
      'Sensor': 'Optical',
    },
    rating: 4.6,
    reviewCount: 289,
    sku: 'GM-005',
  },
  {
    id: '6',
    name: 'USB-C Hub 7-in-1',
    slug: 'usb-c-hub-7-in-1',
    description: 'Expand your laptop connectivity with this versatile USB-C hub. Features HDMI 4K, 3x USB 3.0, SD/TF card readers, and 100W PD charging.',
    shortDescription: '7-port USB-C hub with 4K HDMI',
    categoryId: '3',
    subCategoryId: '3-4',
    price: 2999,
    discountPrice: 2499,
    discountPercentage: 17,
    images: ['usb-hub', 'usb-c-adapter', 'laptop-accessories'],
    inStock: true,
    stockQuantity: 123,
    isOnSale: true,
    isFeatured: false,
    isNew: false,
    specifications: {
      'HDMI': '4K@60Hz',
      'USB Ports': '3x USB 3.0',
      'Card Reader': 'SD/TF',
      'Power Delivery': '100W',
      'Material': 'Aluminum',
    },
    rating: 4.4,
    reviewCount: 512,
    sku: 'HUB-006',
  },
  {
    id: '7',
    name: 'Portable SSD 1TB',
    slug: 'portable-ssd-1tb',
    description: 'Ultra-fast external SSD with read speeds up to 1050MB/s. Compact aluminum design. USB 3.2 Gen 2 interface. Password protection and AES encryption.',
    shortDescription: 'High-speed 1TB external SSD',
    categoryId: '5',
    subCategoryId: '5-1',
    price: 11999,
    discountPrice: 9999,
    discountPercentage: 17,
    images: ['external-ssd', 'storage-device', 'portable-drive'],
    inStock: true,
    stockQuantity: 56,
    isOnSale: true,
    isFeatured: true,
    isNew: false,
    variants: [
      {
        type: 'Capacity',
        options: [
          { name: '500GB', priceModifier: -3000, inStock: true },
          { name: '1TB', priceModifier: 0, inStock: true },
          { name: '2TB', priceModifier: 10000, inStock: true },
        ],
      },
    ],
    specifications: {
      'Capacity': '1TB',
      'Interface': 'USB 3.2 Gen 2',
      'Read Speed': 'Up to 1050MB/s',
      'Write Speed': 'Up to 1000MB/s',
      'Encryption': 'AES 256-bit',
    },
    rating: 4.9,
    reviewCount: 678,
    sku: 'SSD-007',
  },
  {
    id: '8',
    name: 'Smart Watch Pro',
    slug: 'smart-watch-pro',
    description: 'Advanced smartwatch with AMOLED display, heart rate monitoring, GPS, and 7-day battery life. Track your fitness, sleep, and receive notifications.',
    shortDescription: 'Feature-packed smartwatch with AMOLED display',
    categoryId: '6',
    subCategoryId: '6-1',
    price: 15999,
    discountPrice: 12999,
    discountPercentage: 19,
    images: ['smart-watch', 'fitness-watch', 'wearable-tech'],
    inStock: true,
    stockQuantity: 28,
    isOnSale: true,
    isFeatured: true,
    isNew: true,
    variants: [
      {
        type: 'Color',
        options: [
          { name: 'Black', inStock: true },
          { name: 'Silver', inStock: true },
          { name: 'Rose Gold', inStock: false },
        ],
      },
      {
        type: 'Band',
        options: [
          { name: 'Sport Band', inStock: true },
          { name: 'Leather Band', priceModifier: 1000, inStock: true },
          { name: 'Metal Band', priceModifier: 2000, inStock: true },
        ],
      },
    ],
    specifications: {
      'Display': '1.4" AMOLED',
      'Battery': '7 days',
      'Water Resistance': '5ATM',
      'Sensors': 'Heart Rate, SpO2, GPS',
      'Connectivity': 'Bluetooth 5.0',
    },
    rating: 4.7,
    reviewCount: 345,
    sku: 'SW-008',
  },
  {
    id: '9',
    name: 'Bluetooth Speaker Waterproof',
    slug: 'bluetooth-speaker-waterproof',
    description: '360° sound with deep bass. IPX7 waterproof rating perfect for pool parties. 24-hour battery life. Pair two speakers for stereo sound.',
    shortDescription: 'Waterproof portable Bluetooth speaker',
    categoryId: '2',
    subCategoryId: '2-3',
    price: 5499,
    discountPrice: 4299,
    discountPercentage: 22,
    images: ['bluetooth-speaker', 'portable-speaker', 'wireless-speaker'],
    inStock: true,
    stockQuantity: 92,
    isOnSale: true,
    isFeatured: false,
    isNew: false,
    specifications: {
      'Output': '20W',
      'Bluetooth': '5.0',
      'Battery': '24 hours',
      'Water Resistance': 'IPX7',
      'Frequency': '60Hz-20kHz',
    },
    rating: 4.5,
    reviewCount: 734,
    sku: 'BS-009',
  },
  {
    id: '10',
    name: 'Laptop Stand Aluminum',
    slug: 'laptop-stand-aluminum',
    description: 'Ergonomic laptop stand to improve posture and airflow. Adjustable height and angle. Compatible with all laptops 10-17 inches. Premium aluminum construction.',
    shortDescription: 'Adjustable ergonomic laptop stand',
    categoryId: '3',
    subCategoryId: '3-5',
    price: 2199,
    images: ['laptop-stand', 'desk-accessories', 'ergonomic-stand'],
    inStock: true,
    stockQuantity: 145,
    isOnSale: false,
    isFeatured: false,
    isNew: false,
    specifications: {
      'Material': 'Aluminum Alloy',
      'Height Range': '2.5" - 6"',
      'Compatibility': '10-17 inch laptops',
      'Weight Capacity': '10kg',
      'Color': 'Space Gray',
    },
    rating: 4.6,
    reviewCount: 456,
    sku: 'LS-010',
  },
  {
    id: '11',
    name: '4K Webcam with Microphone',
    slug: '4k-webcam-with-microphone',
    description: 'Crystal-clear 4K video calls with auto-focus and light correction. Built-in dual microphones with noise reduction. Perfect for streaming and video conferencing.',
    shortDescription: 'Professional 4K webcam for video calls',
    categoryId: '3',
    subCategoryId: '3-3',
    price: 6999,
    discountPrice: 5499,
    discountPercentage: 21,
    images: ['webcam', '4k-camera', 'video-conference'],
    inStock: true,
    stockQuantity: 41,
    isOnSale: true,
    isFeatured: false,
    isNew: true,
    specifications: {
      'Resolution': '4K@30fps',
      'Microphone': 'Dual stereo',
      'Field of View': '90°',
      'Auto Focus': 'Yes',
      'Connection': 'USB-A',
    },
    rating: 4.7,
    reviewCount: 298,
    sku: 'WC-011',
  },
  {
    id: '12',
    name: 'Wireless Charger 15W',
    slug: 'wireless-charger-15w',
    description: 'Fast wireless charging pad with 15W output. Compatible with all Qi-enabled devices. LED indicator and over-charge protection. Slim and compact design.',
    shortDescription: '15W fast wireless charging pad',
    categoryId: '1',
    subCategoryId: '1-4',
    price: 1799,
    discountPrice: 1399,
    discountPercentage: 22,
    images: ['wireless-charger', 'charging-pad', 'phone-charger'],
    inStock: true,
    stockQuantity: 203,
    isOnSale: true,
    isFeatured: false,
    isNew: false,
    specifications: {
      'Output': '15W max',
      'Input': 'USB-C',
      'Compatibility': 'Qi-enabled devices',
      'Safety': 'Over-charge protection',
      'LED Indicator': 'Yes',
    },
    rating: 4.3,
    reviewCount: 621,
    sku: 'WC-012',
  },
];
